Feature/unit test
Star-Academy/Summer1400-SE-Team12 pull request #2
Opened 2021-08-01 06:43 UTC by zkhotanlou

2021-08-03 13:24 UTC, hoseinaghaei commented on src/Phase02/Filterizer.java
> +            minusFilter.filter(invertedIndex.getInvertedIndexValue(minusQuery), answersDocumentsName);
به نظرم بهتره این فور زدن ها تو کلاس مربوطه بره، اینجا خوانایی کد رو اورده پایین

2021-08-03 13:24 UTC, hoseinaghaei commented on src/Phase02/QueryCategorizer.java
> +            if (queryIterator.contains("+")) {
یادتون باشه سوییچ زدن در عموم مواقع خیلی خیلی سریع تر از ایف هست البته تو سوییچ اون چیزی که روش سوییچ زدین باید کامپایل تایم معلوم باشه مثل اینجا که میدونیم یا + هست یا - یا هیچکدوم
و یادتون باشه سوییچ یا ایف الس های پشت سرهم اصلا خوب نیست و تا حد امکان باید ازش خوودداری بشه
اینجا تقریبا ناچارین

2021-08-03 13:24 UTC, hoseinaghaei commented on src/Phase02/QueryCategorizer.java
> +        queryKeeper.addAllSets(plusContain,minusContain,withoutContain);
شما اینجا هم دارین کوئری میزنین هم یچیزی پر میکنین و اینم کار خوبی نیست
کار بهتر اینه ابجکت
QueryKeeper
تو ته همین تابع نیو بشه و ریترن بشه 
بجای اینکه اونو تو این کلاس الکی نگه دارین چون هیچ فایده ای برای این کلاس نداره

2021-08-03 13:24 UTC, hoseinaghaei commented on src/Tests/FileReaderTest.java
> +        String textFileExpected = "JUnit provides a tool for execution of your test cases";
expected value
هارو فاینال تعریف کنین تا قابل تشخیص باشن

2021-08-03 13:24 UTC, hoseinaghaei commented on src/Tests/FilterizerTest.java
> +
این نیو کردن هش ست رو میتونین بسپارین به ی تابع دیگه
کلا هرچقدر میتونین طول توابع رو کم کنین
نگین خب ۱۰ خط مجازه منم هرچی دلم خواست مینویسم

2021-08-03 13:24 UTC, hoseinaghaei commented on src/Tests/FilterizerTest.java
> +            Set<String> arg1 = (HashSet) invocation.getArguments()[1];
نمیفهمم دارین چیکار میکنین
این کارا برای چیع؟
ی ماک کردن ساده دیگه

2021-08-03 13:24 UTC, hoseinaghaei commented on src/Tests/FilterizerTest.java
> +        withoutSignContain.clear();
بار هزارم
اولا از یک متغییر تمپ چه تو یک تابع و چه تو دو تا تابع چندبار استفاده نکنین
و دوما این تمپ ها نیاز نیست گلوبال باشن 
این یکی بار ۱۰۰۱امه

2021-08-03 13:24 UTC, hoseinaghaei commented on src/Tests/InvertedIndexTest.java
> +public class InvertedIndexTest {
تو این کلاس بالاخره همه چی سرجاشه
اینطوری بزنین همیشه:))

2021-08-03 13:24 UTC, hoseinaghaei commented on src/Tests/QueryCategorizerTest.java
> +        System.setIn(new ByteArrayInputStream(query.getBytes()));
ببینین در کل نمیان 
IO
رو تست بکنن مخصوصا رو کنسول
و اینم یگم که وظیفه کلاس 
QueryCategorizer
نیست بره از ورودی بخونه
باید ی ایترفیس بذارین کارش خوندن و نوشتن باشه و اینجا تو کلاس 
QueryCategorizer
ازش استفاده کنید و موقع تست هم ماکش کنید

2021-08-04 08:09 UTC, Parsa2820 requested changes
تستاتون کامل بود. خسته نباشید

2021-08-04 08:09 UTC, Parsa2820 commented on src/Tests/WithoutSignFilterTest.java
> +        this.withoutSignFilter = new WithoutSignFilter();
<p dir="rtl">
this اضافس
</p>

2021-08-04 08:09 UTC, Parsa2820 commented on src/Tests/WithoutSignFilterTest.java
> +        this.withoutSignFilter.filter(documentsContainWithoutSignQuery,preFiltered);
<p dir="rtl">
this اضافس
</p>

2021-08-04 08:09 UTC, Parsa2820 commented on src/Tests/WithoutSignFilterTest.java
> +        this.withoutSignFilter.filter(documentsContainWithoutSignQuery,preFiltered);
<p dir="rtl">
this اضافس
</p>

2021-08-04 08:09 UTC, Parsa2820 commented on src/Tests/WithoutSignFilterTest.java
> +        this.withoutSignFilter.filter(documentsContainWithoutSignQuery,preFiltered);
<p dir="rtl">
this اضافس
</p>

2021-08-04 08:09 UTC, Parsa2820 commented on src/Tests/WithoutSignFilterTest.java
> +        this.withoutSignFilter.filter(documentsContainWithoutSignQuery,preFiltered);
<p dir="rtl">
this اضافس
</p>

2021-08-04 08:09 UTC, Parsa2820 commented on src/Tests/WithoutSignFilterTest.java
> +        Assert.assertArrayEquals(expectedFiltered.toArray(), actualFiltered.toArray());
<p dir="rtl">
برای بررسی برابری set چرا به array تبدیل کردید؟
set ترتیب نداره ولی array داره. ممکنه بعضی وقتا دو تا  set برابر باشن ولی به array تبدیل بشن برابر نباشن.
کلا تبدیل set به array هم یه پردازش اضافیه.
</p>

2021-08-04 08:09 UTC, Parsa2820 commented on src/Tests/WithoutSignFilterTest.java
> +        Assert.assertArrayEquals(expectedFiltered.toArray(), actualFiltered.toArray());
<p dir="rtl">
برای بررسی برابری set چرا به array تبدیل کردید؟
set ترتیب نداره ولی array داره. ممکنه بعضی وقتا دو تا  set برابر باشن ولی به array تبدیل بشن برابر نباشن.
کلا تبدیل set به array هم یه پردازش اضافیه.
</p>

2021-08-04 08:09 UTC, Parsa2820 commented on src/Tests/WithoutSignFilterTest.java
> +        Assert.assertArrayEquals(expectedFiltered.toArray(), actualFiltered.toArray());
<p dir="rtl">
برای بررسی برابری set چرا به array تبدیل کردید؟
set ترتیب نداره ولی array داره. ممکنه بعضی وقتا دو تا  set برابر باشن ولی به array تبدیل بشن برابر نباشن.
کلا تبدیل set به array هم یه پردازش اضافیه.
</p>

2021-08-04 08:09 UTC, Parsa2820 commented on src/Tests/WithoutSignFilterTest.java
> +        Assert.assertArrayEquals(expectedFiltered.toArray(), actualFiltered.toArray());
<p dir="rtl">
برای بررسی برابری set چرا به array تبدیل کردید؟
set ترتیب نداره ولی array داره. ممکنه بعضی وقتا دو تا  set برابر باشن ولی به array تبدیل بشن برابر نباشن.
کلا تبدیل set به array هم یه پردازش اضافیه.
</p>

2021-08-04 08:09 UTC, Parsa2820 commented on src/Tests/PlusFilterTest.java
> +public class PlusFilterTest {
<p dir="rtl">
ایراداتی که به کلاس WithoutSignFilterTest گرفتم اینجا هم هستن. 
</p>

2021-08-04 08:09 UTC, Parsa2820 commented on src/Tests/InvertedIndexTest.java
> +        Assert.assertArrayEquals(new String[]{"text3", "text1"},
اینجا هم بدون ترتیب بودن ست میتونه مشکل ایجاد کنه

2021-08-04 08:09 UTC, Parsa2820 commented on src/Tests/InvertedIndexTest.java
> +                invertedIndex.getInvertedIndexValue("six").toArray());
اینجا هم تبدیل به آرایه پردازش اضافیه ولی مشکلی ایجاد نمیکنه

2021-08-04 08:09 UTC, Parsa2820 commented on src/Tests/InvertedIndexTest.java
> +                invertedIndex.getInvertedIndexValue("ten").toArray());
اینجا هم تبدیل به آرایه پردازش اضافیه ولی مشکلی ایجاد نمیکنه

2021-08-04 08:09 UTC, Parsa2820 commented on src/Tests/FileReaderTest.java
> +        Assert.assertTrue(actualValue.containsValue(textFileExpected.toLowerCase()));
بررسی کنید که مقدار با کلید درستی مپ شده

2021-08-04 08:09 UTC, Parsa2820 commented on src/Tests/FileReaderTest.java
> +        final String PATH_OF_FILE = "src\\TesterFile";
Java convention for naming local variables

PATH_OF_FILE -> pathOfFile or simply filePath

2021-08-04 08:09 UTC, Parsa2820 commented on src/Tests/WithoutSignFilterTest.java
> +        Set<String> actualFiltered = preFiltered;
<p dir="rtl">
برای actualFiltered شی جدید بسازید. اینجوری اگه preFiltered داخل یکی از تابع ها تغییر کنه، دیباگ کردن واستون خیلی سخت میشه. 
</p>

2021-08-04 08:09 UTC, Parsa2820 commented on src/Tests/WithoutSignFilterTest.java
> +        Set<String> actualFiltered = preFiltered;
<p dir="rtl">
برای actualFiltered شی جدید بسازید. اینجوری اگه preFiltered داخل یکی از تابع ها تغییر کنه، دیباگ کردن واستون خیلی سخت میشه. 
</p>

2021-08-04 08:09 UTC, Parsa2820 commented on src/Tests/WithoutSignFilterTest.java
> +        Set<String> actualFiltered = preFiltered;
<p dir="rtl">
برای actualFiltered شی جدید بسازید. اینجوری اگه preFiltered داخل یکی از تابع ها تغییر کنه، دیباگ کردن واستون خیلی سخت میشه. 
</p>

2021-08-04 08:09 UTC, Parsa2820 commented on src/Tests/WithoutSignFilterTest.java
> +        Set<String> actualFiltered = preFiltered;
<p dir="rtl">
برای actualFiltered شی جدید بسازید. اینجوری اگه preFiltered داخل یکی از تابع ها تغییر کنه، دیباگ کردن واستون خیلی سخت میشه. 
</p>

2021-08-04 08:09 UTC, Parsa2820 commented on src/Tests/MinusFilterTest.java
> +public class MinusFilterTest {
<p dir="rtl">
ایراداتی که به کلاس WithoutSignFilterTest گرفتم اینجا هم هستن. 
</p>

2021-08-04 08:09 UTC, Parsa2820 commented on src/Tests/QueryCategorizerTest.java
> +        System.setIn(new ByteArrayInputStream(query.getBytes()));
منم با حسین موافقم

2021-08-04 08:09 UTC, Parsa2820 commented on src/Tests/FilterizerTest.java
> +public class FilterizerTest {
<p dir="rtl">
ایراداتی که به کلاس WithoutSignFilterTest گرفتم اینجا هم هستن. 
(مشکل مربوط به toArray)
</p>

2021-08-07 07:04 UTC, nedataghizadeh79 commented on src/Phase02/Filterizer.java
> +            minusFilter.filter(invertedIndex.getInvertedIndexValue(minusQuery), answersDocumentsName);
ba salam object invertedIndex dar hamin class new shode va dar sorate anjam in taghirat bayad kole memari filter ha taghir konan hamchenin tamami in taghirat dar phase5 emal shode.

2021-08-07 07:29 UTC, nedataghizadeh79 commented on src/Tests/QueryCategorizerTest.java
> +        System.setIn(new ByteArrayInputStream(query.getBytes()));
والا تو اینترنت خیلی از این مدل تستایی که مربوط به ورودی خروجی گرفتن بود دیدم و اون خط مربوطه هم با ایده گرفتن از نمونه کدهای تو نت نوشتم اگر ننویسم تابع ران میشه اما پایان پیدا نمیکنه.
تو این کلاس این تابعی که داره ورودی میگیره پابلیکه و درون این تابع ما یک تابع پرایوت دیگر فراخوانی کردیم و مجبور بویم اسکنر گرفتن هم تست کنیم که تابع دیگرمان هم صحتش بررسی بشه.

2021-08-07 07:31 UTC, zkhotanlou commented on src/Tests/WithoutSignFilterTest.java
> +        Set<String> actualFiltered = preFiltered;
بله ممنون از تذکرتون اما در این فاز عملکرد این تابع به  این صورته که ورودی تابع تغییر داده بشه و برای تست بررسی شده که تغییرات درست اعمال شدن یا خیر، البته این نکات در پیاده سازی فاز5 اعمال شده

2021-08-08 09:12 UTC, hoseinaghaei approved these changes

2021-08-08 09:12 UTC, hoseinaghaei commented on code-star.iml
> +<?xml version="1.0" encoding="UTF-8"?>
این فایل ها تو گیت ایگنور نباید باشه؟

2021-08-08 09:12 UTC, hoseinaghaei commented on src/Tests/FilterizerTest.java
> +        Mockito.when(mockedQueryKeeper.getMinusContain()).thenReturn(new HashSet<>(Arrays.asList("1")));
بهتره این عملیات های 
setup
بره تو ی تابع دیگه
ولی الان نمیخواد تغییر بدین، همشون بره فاز۵

2021-08-08 09:12 UTC, hoseinaghaei commented on src/Tests/FilterizerTest.java
> +        Mockito.when(mockedQueryKeeper.getMinusContain()).thenReturn(new HashSet<>());
همون کامنت بالا
برن تو ی تابع دیگ

2021-08-09 10:08 UTC, merged