Phase05
Star-Academy/Summer1400-SE-Team12 pull request #5
Opened 2021-08-07 07:54 UTC by zkhotanlou

2021-08-08 11:47 UTC, rahaahmadi commented on Phase05/Phase05/Phase05/FileReader.cs
> +                throw;
کنید throw میکنید دیگه لازم نیست  catch وقتی

2021-08-08 11:47 UTC, rahaahmadi commented on Phase05/Phase05/Phase05/FilterHandler.cs
> +            return finalFiltered.Except(minusFiltered).Intersect(plusFiltered).ToHashSet();
کنید return برای خوانایی بیشتر بهتره اول تو یه متغیر بریزید بعد

2021-08-08 11:47 UTC, rahaahmadi commented on Phase05/Phase05/Phase05/SearchEngine.cs
> +            _ioHandler.PrintResultDocuments(answers);
بهتره که این تابع خروجی داشته باشه و پرینت اینجا صدا زده نشه

2021-08-08 13:11 UTC, rahaahmadi commented on Phase05/Phase05/TestPhase05/FilterHandlerTest.cs
> +        private void SetupIFilter_FilterMethod(ISet<string> m,ISet<string>p)
اسم بهتر بذارید p و m به جای

2021-08-10 20:34 UTC, hoseinaghaei requested changes
اوایل خوب پیش رفتید خوشحال شدم، تهش دیگه گل کاشتین

2021-08-10 20:34 UTC, hoseinaghaei commented on Phase05/Phase05/Phase05/DisjunctionFilter.cs
> +                current.Union(_invertedIndex.GetInvertedIndexValue(query)).ToHashSet());
به به لذت بردیم افرین

2021-08-10 20:34 UTC, hoseinaghaei commented on Phase05/Phase05/Phase05/FileReader.cs
> +                    documents.Add(Path.GetFileName(filePath), File.ReadAllText(filePath));
چرا کل اینو با لینک و تابع 
toDictionary
نمیزنید؟

2021-08-10 20:34 UTC, hoseinaghaei commented on Phase05/Phase05/Phase05/FilterHandler.cs
> +        private ISet<string> GeneralizeSignFiltered(ISet<string> plusFiltered, ISet<string> minusFiltered,
اسم بهتر توروخدا برای تابع بذارین

2021-08-10 20:34 UTC, hoseinaghaei commented on Phase05/Phase05/Phase05/IIOHandler.cs
> +    public interface IIOHandler
به به واقعا لذت داریم میبریم واقعا

2021-08-10 20:34 UTC, hoseinaghaei commented on Phase05/Phase05/Phase05/IIOHandler.cs
> +        void PrintResultDocuments(ISet<string> answers);
اما اینجا لذت نبریم
چونکه پرینت و خوندن کوئری ربطی به خوندن فایل نداره
ببینید s
توی 
solid
به این معناست که کلاس باید فقط یک کار انجام بده

اما حالا این کار چطوری تعیین میشه؟ باید دید کی مشتری این اینترفیس هست
الان باید مشتری تابع اول با مشتری دوتا تابع دیگ متفاوت باشه قطعا 
بهتره که دوتا اینترفیس کنین

2021-08-10 20:34 UTC, hoseinaghaei commented on Phase05/Phase05/Phase05/IInvertedIndex.cs
> +        HashSet<string> GetInvertedIndexValue(string key);
اسم بهتر

2021-08-10 20:34 UTC, hoseinaghaei commented on Phase05/Phase05/Phase05/IOHandler.cs
> +        public Dictionary<string, string> ReadDocuments(string path)
چرا دقیقا این خوندن رو اینطوری دو قسمت کردین؟
اینترفیس 
IOHandler
یکم مشکل داره
حلش کنین

2021-08-10 20:34 UTC, hoseinaghaei commented on Phase05/Phase05/Phase05/IQueryKeeper.cs
> +    public interface IQueryKeeper
برای کلاس های 
DTO
دیگه اینترفیس نمیذارن که

2021-08-10 20:34 UTC, hoseinaghaei commented on Phase05/Phase05/Phase05/InvertedIndex.cs
> +                    _invertedIndexMap.GetValueOrDefault(word,new HashSet<string>()).Add(docName);
اینو کی زده؟ جرئت داری یعنی بگو 😒
یدونه ایراد میگیرم درحالی که کلا ایراده، برین کلا این تابع رو ریفکتور کنین 
الان وقتی وارد ایف خط ۲۸ میشه یعنی قطعا کلمه وجود داره
خب چرا دیگه تابع 
GetValueOrDefault
استفاده شده؟
وقتی به قابلیت یک تابع نیاز ندارین ولی ازش استفاده میکنین این سربار الکیه چون این تابع تو خودش داره باز وجود داشتن یا نداشتن کلمه رو تست میکنه

2021-08-10 20:34 UTC, hoseinaghaei commented on Phase05/Phase05/Phase05/Program.cs
> +        private const string FilePath = @"D:\programming\java\code-star\src\EnglishData";
Really?
بعد ۵ فاز هنور ادرس رو به صورت هارد کد میدین؟

2021-08-10 20:34 UTC, hoseinaghaei commented on Phase05/Phase05/Phase05/QueryKeeper.cs
> +        public HashSet<string> GetPlusContain()
سی شارپ اومد پراپرتی گذاشت که مثل جاوا گت و ست نذاریم
بعد شما افتخار نمیدین ازش استفاده کنین؟

2021-08-10 20:34 UTC, hoseinaghaei commented on Phase05/Phase05/Phase05/SearchEngine.cs
> +    public class SearchEngine
هزاران بار گفتم 
ما به یک فرد از بیرون پروژه خودمون باید یک اینترفیس بدیم نه کلاس و پیاده سازی

2021-08-10 20:34 UTC, hoseinaghaei commented on Phase05/Phase05/TestPhase05/ConjunctionFilterTest.cs
> +            var withoutSignFilterQuery = new HashSet<string>() {"hello", "bye"};
این متغییر ها باید ی ویژگی داشته باشن
چیه اون؟

2021-08-10 20:34 UTC, hoseinaghaei commented on Phase05/Phase05/TestPhase05/FileReaderTest.cs
> +            string path = "TestFiles";
باید چی باشه؟

2021-08-10 20:34 UTC, hoseinaghaei commented on Phase05/Phase05/TestPhase05/FileReaderTest.cs
> +            Dictionary<string,string> documents = _fileReader.ReadFile(path);
var 
را پاس بداریم

2021-08-10 20:34 UTC, hoseinaghaei commented on Phase05/Phase05/TestPhase05/FilterHandlerTest.cs
> +            SetupIQueryKeeper_GetMethods(minusQuery,plusQuery);
کی گفته اسم تابع عادی رو اندرلاین بذارین؟

2021-08-10 20:34 UTC, hoseinaghaei commented on Phase05/Phase05/TestPhase05/FilterHandlerTest.cs
> +        private void SetupIQueryKeeper_GetMethods(ISet<string> minusQuery,ISet<string>plusQuery)
ی فاصله بین تایپ و اسم بذارین خواهشا

2021-08-10 20:34 UTC, hoseinaghaei commented on Phase05/Phase05/TestPhase05/InvertedIndexTest.cs
> +        public void TestBuildInvertedIndex_WordExistInADoc() {
اسم رو به شیوه که تو کارگاه گفتم بذارین

2021-08-10 20:34 UTC, hoseinaghaei commented on Phase05/Phase05/TestPhase05/InvertedIndexTest.cs
> +            Assert.Equal(new HashSet<string>(){"text2"},
expected & actual 
رو به صورت متغییر تعریف کنین تا خوانا تر باشه

2021-08-10 20:34 UTC, hoseinaghaei commented on Phase05/Phase05/TestPhase05/InvertedIndexTest.cs
> +            _docNameMapToContent = new Dictionary<string, string>
ی تابع صدا بزنین حداقل
داخل کانستراکتور اینطوری شلوغ نکنین

2021-08-10 20:34 UTC, hoseinaghaei commented on Phase05/Phase05/TestPhase05/InvertedIndexTest.cs
> +        [Fact]
این ۳ تا تابع میتونه به کمک 
throry
بشه یک تابع و کلا اون دیکشنری گلوبال هم بیاد داخل اون تابع
حتما این کارو بکنید

2021-08-10 20:34 UTC, hoseinaghaei commented on Phase05/Phase05/TestPhase05/QueryCategorizerTest.cs
> +            Assert.Equal(new HashSet<string>() {"sisi", "sister"},categorized.GetPlusContain());
expected & actual
رو به صورت متغییر تعریف کنین تا خوانا تر باشه

2021-08-11 06:22 UTC, nedataghizadeh79 commented on Phase05/Phase05/TestPhase05/FileReaderTest.cs
> +            string path = "TestFiles";
چرا نمیفهمم چی داری میگی :/ شفافتر لطفا

2021-08-11 07:01 UTC, Parsa2820 approved these changes
<p dir="rtl">
خوب بود خسته نباشید. سعی کنید از namespace مختلف برای کلاس یا اینترفیسای مختلف استفاده کنید.
</p>

2021-08-11 07:01 UTC, Parsa2820 commented on Phase05/Phase05/Phase05/FileReader.cs
> +                foreach (string filePath in Directory.GetFiles(path))
با لینک هم میتونید بنویسید

Directory.GetFiles(path).ToDictionary(filePath => Path.GetFileName(filePath), filePath => File.ReadAllText(filePath));

2021-08-11 07:01 UTC, Parsa2820 commented on Phase05/Phase05/Phase05/IQueryKeeper.cs
> +        HashSet<string> GetPlusContain();
<p dir="rtl">
اگه فقط قراره getter داشته باشه میتونید از property استفاده کنید.
</p>

2021-08-11 07:01 UTC, Parsa2820 commented on Phase05/Phase05/TestPhase05/FileReaderTest.cs
> +            string path = "TestFiles";
final

2021-08-11 07:36 UTC, nedataghizadeh79 commented on Phase05/Phase05/Phase05/FilterHandler.cs
> +        private ISet<string> GeneralizeSignFiltered(ISet<string> plusFiltered, ISet<string> minusFiltered,
بخدا اسمش خوبه :(

2021-08-11 07:36 UTC, nedataghizadeh79 commented on Phase05/Phase05/Phase05/IInvertedIndex.cs
> +        HashSet<string> GetInvertedIndexValue(string key);
:؟

2021-08-17 08:41 UTC, hoseinaghaei approved these changes

2021-08-17 10:07 UTC, merged