Phase08
Star-Academy/Summer1400-SE-Team12 pull request #7
Opened 2021-08-16 18:21 UTC by zkhotanlou

2021-08-17 08:33 UTC, rahaahmadi commented on Phase08/Phase08/Phase08/IConnectorDataAndSearchEngine.cs
> +    }
!!خالیه
تابع هاشو بزارید

2021-08-17 08:33 UTC, rahaahmadi commented on Phase08/Phase08/Phase08/IOHandler.cs
> +                    Console.Write(answer + "  ");
: به جای فور میتونید بزنید
Console.WriteLine(string.Join("  ", answers));

2021-08-17 08:33 UTC, rahaahmadi commented on Phase08/Phase08/Phase08/Program.cs
> +            var searchEngine = new SearchEngine(ioHandler,queryCategorizer, filterHandler);
بهتره تا اینکه خود کلاس رو بدین searchEngine اول ورودی بخونه بعد اونو بدین به  IO به نظرم اگه

2021-08-17 08:33 UTC, rahaahmadi commented on Phase08/Phase08/SQLHandler/Document.cs
> +        }
کانستراکتور فکر نکنم لازم داشته باشه

2021-08-17 08:33 UTC, rahaahmadi commented on Phase08/Phase08/SQLHandler/InvertedIndexContext.cs
> +        }
باشه InvertedIndex این تابع بهتره تو کلاس

2021-08-17 08:33 UTC, rahaahmadi commented on Phase08/Phase08/SQLHandler/Program.cs
> +    }
این کلاس اضافیه 
یه پروژه جدا زدین  sql handler فکنم شما برای 
بهتره یه فولدر جدا تو همون پروژه اصلی باشه، لازم نیست یه پروژه جدا بزنین

2021-08-17 08:33 UTC, rahaahmadi commented on Phase08/Phase08/SQLHandler/Word.cs
> +        }
وقتی فیلدا پابلیکه چرا از کانستراکتور میگیرین؟

2021-08-17 08:33 UTC, rahaahmadi commented on Phase08/Phase08/TestEFCorePhase08/ContextFactory.cs
> +    public static class ContextFactory
این کلاس برا چیه؟ میتونستید از مموری استفاده کنید

2021-08-17 08:33 UTC, rahaahmadi commented on Phase08/Phase08/TestEFCorePhase08/FileReaderTest.cs
> +            Assert.Equal(contentExpected, documents.GetValueOrDefault(fileNameExpected));
دو تا تقریبا عین هم هستن 
بهتر بود یه تست برا حالتی که فایل وجود نداره بزارین

2021-08-17 08:54 UTC, nedataghizadeh79 commented on Phase08/Phase08/TestEFCorePhase08/ContextFactory.cs
> +    public static class ContextFactory
این کلاس برای یکی از تستاست  در واقع زمانی که میخواستیم چک کنیم دیتا ساخته شده تو جدول اگر همان کلاس کاانتنت را فرا میخواندیم ارور میخواردیم چون جداول در هم قاطی میشدند اما با کمک این کلاس تابع آن کانفیگورینگو جدا کردیم که این مشکل دیگه پیش نیاد و از آن مموری هم استفاده کردیم ♥

2021-08-17 08:55 UTC, hoseinaghaei requested changes

2021-08-17 08:55 UTC, hoseinaghaei commented on Phase08/Phase08/Phase08/ConnectorDataAndSearchEngine.cs
> +    public class ConnectorDataAndSearchEngine : IConnectorDataAndSearchEngine
alan esm shoma khodesh dare S solid ro naghz mikone niaz nis berim jolotar.

2021-08-17 08:55 UTC, hoseinaghaei commented on Phase08/Phase08/Phase08/ConnectorDataAndSearchEngine.cs
> +        public ISet<string> Connect(string folderPath)
connect vazifash nis search kone

2021-08-17 08:55 UTC, hoseinaghaei commented on Phase08/Phase08/Phase08/DataHandler.cs
> +        private bool IsDataBaseInitialized()
behtare to InvertedIndexContext ye tabe bezarin ke ino beheton bege, jay inke dasti check konin

2021-08-17 08:55 UTC, hoseinaghaei commented on Phase08/Phase08/Phase08/DataHandler.cs
> +        private bool IsDataBaseInitialized()
va inke behtare roy classi mesl context ye wrapper bekeshin va faghat on ghabeliat haei ke niaz darin ro be baghie class ha bedin

2021-08-17 08:55 UTC, hoseinaghaei commented on Phase08/Phase08/Phase08/DisjunctionFilter.cs
> +                    ToHashSet());
afarin
inja ke GetDocumentsContainQuery to class khoadesh gozashti kar khobie
faghat hatman wrapper bekeshin rosh va ye interface bezarin barash ke be ye class depend nabashe

2021-08-17 08:55 UTC, hoseinaghaei commented on Phase08/Phase08/Phase08/FileReader.cs
> +            catch (FileNotFoundException filException)
tanha exception ke mitone throw beshe hamine?

2021-08-17 08:55 UTC, hoseinaghaei commented on Phase08/Phase08/Phase08/FilterHandler.cs
> +            var finalFiltered = new HashSet<string>(withoutSignFiltered);
inkar daghighan che sodi dare?

2021-08-17 08:55 UTC, hoseinaghaei commented on Phase08/Phase08/Phase08/InvertedIndex.cs
> +    public class InvertedIndex : IInvertedIndex
in class kheili kar nemikone?

2021-08-17 08:55 UTC, hoseinaghaei commented on Phase08/Phase08/SQLHandler/InvertedIndexContext.cs
> +        }
bayad ye wrapper biad ro context va tamam ertebat ba in calss ro on handle kone.

2021-08-17 08:58 UTC, nedataghizadeh79 commented on Phase08/Phase08/SQLHandler/Program.cs
> +    }
بخاطر اینکه پارسا گفت از نیم اسپیس های دیگه هم استفاده کنید ما اومدیم این کارو کردیم، و اگه این کلاس نباشه ارور میده و 
 وجودش الزامیه حتی اگ کاری نکنه

2021-08-17 09:03 UTC, nedataghizadeh79 commented on Phase08/Phase08/TestEFCorePhase08/FileReaderTest.cs
> +            Assert.Equal(contentExpected, documents.GetValueOrDefault(fileNameExpected));
عزیزم در واقع تابع اول داره چک میکنه که آيا اسم فایل درست داده شده و ایا وجود داره یا نه و اینکه به کانتنت درستی مپ شده یا نه و تابع دوم داره دایومنتش به اسمش درست مپ شده یا نه

2021-08-17 09:07 UTC, nedataghizadeh79 commented on Phase08/Phase08/Phase08/InvertedIndex.cs
> +    public class InvertedIndex : IInvertedIndex
**قلب** تپنده ی پروزمونه معلومه که زیاد کار میکنه :)

2021-08-17 09:29 UTC, rahaahmadi commented on Phase08/Phase08/SQLHandler/Program.cs
> +    }
منظورش از نیم اسپیس فکر نکنم یه پروژه دیگه بود چون ما هم اول یه پروژه دیگه زده بودیم پارسا گفت لازم نیست

2021-08-17 11:38 UTC, zkhotanlou commented on Phase08/Phase08/Phase08/FilterHandler.cs
> +            var finalFiltered = new HashSet<string>(withoutSignFiltered);
برای اینکه 
withoutSignFiltered 
ورودی تابع هست می خوایم فیلتر نهایی باعث تغییر ورودی تابع نشه

2021-08-21 07:47 UTC, Parsa2820 reviewed
خوب بود بچه ها. خسته نباشید

2021-08-21 07:47 UTC, Parsa2820 commented on Phase08/Phase08/Phase08/ISearchEngine.cs
> +        ISet<string> Search(string[] queries, string folderPath);
ورودی تابع به جای آرایه اینترفیس باشه

2021-08-21 07:47 UTC, Parsa2820 commented on Phase08/Phase08/Phase08/Program.cs
> +        const string path = @"EnglishData";
<p dir="rtl">
چرا رشته رو verbatim تعریف کردید؟
@ اولشو بردارید
</p>

2021-08-21 07:47 UTC, Parsa2820 commented on Phase08/Phase08/SQLHandler/Program.cs
> +    }
<p dir="rtl">
منظورم از namespace تو همون پروژه بود. اگه بالای فایلتون 
</p>

namespace Phase08.SqlHandler
{
}

<p dir="rtl">
یه namespace ایجاد میشه. کلا هم اگه میخواید پروژه جدید بسازید که قرار نیست اجرا بشه، از classlib استفاده کنید که entry point نداره.
</p>

2021-08-23 10:55 UTC, merged